services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "3000:80"
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/data.sqlite:/app/prisma/data.sqlite
      - ./data/uploads:/app/uploads
