[project]
name = "voicenotes-whisper"
version = "1.0.0"
description = "Standalone transcription service using faster-whisper"
requires-python = ">=3.9"
dependencies = [
  "click",
  "faster-whisper",
  "fastapi",
  "uvicorn[standard]",
  "sse-starlette",
  "python-multipart",
  "python-dotenv",
]
